#!/usr/bin/env bash
#
#   zoek?
#   Dutch, weak verb, present tense
#   to search, look for, to seek
#   
#   Search for native, flatpak and snap packages with one command
#   run this script with the search string as argurment
#   example:
#   zoek packagename    
#   screenshot:
#   https://i.imgur.com/s5gFSzP.png
#   instructions:
#   Save this file as /usr/bin/zoek
#   Set execute permissions: chmod +x /usr/bin/zoek
#   Currently works with linux distributions: Solus, Arch, Debian, Fedora.

STRING1=$1
source /etc/os-release
declare -A osInfo;
osInfo[/usr/bin/eopkg]=eopkg
osInfo[/usr/bin/apt-cache]=apt-cache
osInfo[/usr/bin/dnf]=fedora
osInfo[/usr/bin/pacman]=arch
echo 
for f in ${!osInfo[@]}
do
    if [[ -f $f ]];then
        echo Package manager: ${osInfo[$f]} on $PRETTY_NAME

echo Searching for native packages...
$f search $STRING1
#dirtyhackforarch, arch users are used to it anyway
test -f /usr/bin/dnf && $f -Ss $STRING1
echo 

echo looking for snap packages...
snap search $STRING1
echo 

echo flatpak maybe?
flatpak search $STRING1

    fi
done
echo 
