#!/usr/bin/env bash

<< 'multilinecomment'
    zoek?
    Dutch, weak verb, present tense
    to search, look for, to seek
    
    Search for native, flatpak and snap packages with one command
    run this script with the search string as argurment
    example:
    zoek packagename    
    screenshot:
    https://i.imgur.com/s5gFSzP.png
    
    instructions:
    Save this file as /usr/bin/zoek
    Set execute permissions: chmod +x /usr/bin/zoek
    
    Currently only works with my personal favorite linux distributions: Solus, Debian and Debian derivates.
    Testing Redhat, Fedora and CentOS support
multilinecomment

STRING1=$1
source /etc/os-release
declare -A osInfo;
osInfo[/usr/bin/eopkg]=eopkg
osInfo[/usr/bin/apt-cache]=apt-cache
osInfo[/usr/bin/yum]=redhat #testing: tested on centos
osInfo[/usr/bin/pacman]=arch
echo 
for f in ${!osInfo[@]}
do
    if [[ -f $f ]];then
        echo Package manager: ${osInfo[$f]} on $PRETTY_NAME | lolcat

echo Searching for native packages... | lolcat
$f search $STRING1
#dirtyhackforarch, arch users are used to it anyway
test -f /usr/bin/yum && $f -Ss $STRING1
echo 

echo looking for snap packages... | lolcat
snap search $STRING1
echo 

echo flatpak maybe? | lolcat
flatpak search $STRING1

    fi
done
echo 
